{% set name = "CRYSTALpytools" %}
{% set version = "2024.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/crystalpytools-{{ version }}.tar.gz
  sha256: 4fc74e2def33bf658f6de8835a15251d0521a4096a58612b27ac341b8485d272

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=43.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - sympy
    - scipy <1.14.0
    - matplotlib-base
    - pandas
    - pyyaml
    - mendeleev >=0.14.0
    - pymatgen >=2022.7.25
    - ase >=3.22.1
    - basis_set_exchange >=0.9.1

test:
  imports:
    - CRYSTALpytools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/crystal-code-tools/CRYSTALpytools
  summary: Python tools for the CRYSTAL code developed and mantained by the CRYSTAL code developers.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://crystal-code-tools.github.io/CRYSTALpytools/
  dev_url: https://github.com/crystal-code-tools/CRYSTALpytools

extra:
  recipe-maintainers:
    - crystal-code-tools
